import { APP_NAME } from '@/config/relay-chains';

const SELECTED_ACCOUNT_LOCAL_STORAGE_KEY = `${APP_NAME}-selected-account`;

const DEFAULT_PROXY_ACCOUNT_AMOUNT = 10;

export { DEFAULT_PROXY_ACCOUNT_AMOUNT, SELECTED_ACCOUNT_LOCAL_STORAGE_KEY };
