name: Setup
description: Sets up a Node.js environment, installs the dependencies using Yarn,
             and caches the installed dependencies for faster future builds.
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org
        cache: yarn

    - uses: actions/cache@v4
      id: install-cache
      with:
        path: node_modules/
        key: ${{ runner.os }}-install-${{ hashFiles('**/yarn.lock') }}

    - if: steps.install-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile --ignore-scripts --ignore-engines
      shell: bash
