version: "3.8"
services:
    interbtc:
        image: "registry.gitlab.com/interlay/btc-parachain/standalone:0.6.1"
        command:
            - btc-parachain
            - --dev
            - --unsafe-rpc-external
            - --unsafe-ws-external
            - --rpc-methods
            - Unsafe
        ports:
            - "9933:9933"
            - "9944:9944"
    staked_relayer:
        image: "registry.gitlab.com/interlay/interbtc-clients/staked-relayer:0.6.1"
        command:
            - staked-relayer
            - --keyring
            - eve
            - --polka-btc-url
            - "ws://interbtc:9944"
            - --auto-register-with-stake
            - "100"
        environment: &client-env
            BITCOIN_RPC_URL: http://btc.do.interbtc.io:18332
            BITCOIN_RPC_USER: rpcuser
            BITCOIN_RPC_PASS: rpcpassword
            RUST_LOG: info
        restart: unless-stopped
    oracle:
        image: "registry.gitlab.com/interlay/interbtc-clients/oracle:0.6.1"
        command:
            - oracle
            - --keyring
            - bob
            - --polka-btc-url
            - "ws://interbtc:9944"
        environment:
            RUST_LOG: info
        restart: unless-stopped
    faucet:
        image: "registry.gitlab.com/interlay/interbtc-clients/faucet:0.6.1"
        command:
            - faucet
            - --keyring
            - ferdie
            - --polka-btc-url
            - "ws://interbtc:9944"
            - --user-allowance
            - "1"
            - --vault-allowance
            - "500"
            - --http-addr
            - "[::0]:3035"
        environment:
            RUST_LOG: info
        ports:
            - "3035:3035"
        restart: unless-stopped
    vault:
        image: "registry.gitlab.com/interlay/interbtc-clients/vault:0.6.1"
        command:
            - vault
            - --keyring
            - charlie
            - --network
            - testnet
            - --auto-register-with-collateral
            - "100000000000000"
            - --polka-btc-url
            - "ws://interbtc:9944"
        environment:
            <<: *client-env
        restart: unless-stopped
    postgres:
        image: "postgres:11"
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
    interbtc_stats:
        image: "registry.gitlab.com/interlay/interbtc-stats:0.1.21"
        restart: always
        depends_on:
            - postgres
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; yarn start'
        environment:
            MONITOR: "1"
            ENDPOINT_URL: "ws://interbtc:9944"
            BTC_NETWORK: "http://electrs:3002"
            PGHOST: "postgres"
            PGPORT: "5432"
            PGDATABASE: "postgres"
            PGUSER: "user"
            PGPASSWORD: "password"
        ports:
            - "3007:3007"
