export type { DdProps, DlGroupProps, DlProps, DtProps } from './Dl';
export { Dd, Dl, DlGroup, Dt } from './Dl';
export { Em } from './Em';
export { H1 } from './H1';
export { H2 } from './H2';
export { H3 } from './H3';
export { H4 } from './H4';
export { H5 } from './H5';
export { H6 } from './H6';
export { P } from './P';
export { Span } from './Span';
export { Strong } from './Strong';
export type { TextProps } from './types';
export { resolveTextColor } from './utils';
