export type { DdProps, DlGroupProps, DlProps, DtProps } from './Dl';
export { Dd, Dl, DlGroup, Dt } from './Dl';
export type { EmProps } from './Em';
export { Em } from './Em';
export type { H1Props } from './H1';
export { H1 } from './H1';
export type { H2Props } from './H2';
export { H2 } from './H2';
export type { H3Props } from './H3';
export { H3 } from './H3';
export type { H4Props } from './H4';
export { H4 } from './H4';
export type { H5Props } from './H5';
export { H5 } from './H5';
export type { H6Props } from './H6';
export { H6 } from './H6';
export type { PProps } from './P';
export { P } from './P';
export type { SpanProps } from './Span';
export { Span } from './Span';
export type { StrongProps } from './Strong';
export { Strong } from './Strong';
export type { TextProps } from './types';
