name: Add issues and pull requests to backlog

on:
  issues:
    types:
      - opened
      
jobs:
  add-to-project:
    name: Add issue and pull request to backlog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/interlay/projects/3
          github-token: ${{ secrets.PROJECTS }}
          label: roadmap
          label-operator: NOT
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/interlay/projects/4
          github-token: ${{ secrets.PROJECTS }}
          label: roadmap
          label-operator: AND
