name: Test

on:
  push:
    branches:
      - master
  pull_request:
  # manual trigger
  workflow_dispatch:

env:
  REACT_APP_RELAY_CHAIN_NAME: polkadot
  REACT_APP_PARACHAIN_ID: 2032
  DOCKER_RELAY_CHAIN_CURRENCY: DOT
  REACT_APP_FEATURE_FLAG_LENDING: enabled
  REACT_APP_FEATURE_FLAG_AMM: enabled
  REACT_APP_FEATURE_FLAG_WALLET: enabled

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint
  
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn test:ci
